SET search_path TO public;

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_project_users_project_user ON project_users(project_id, user_id);
CREATE INDEX IF NOT EXISTS idx_units_of_measure_project ON units_of_measure(project_id);
CREATE INDEX IF NOT EXISTS idx_wbs_project_code ON wbs(project_id, code);
CREATE INDEX IF NOT EXISTS idx_wbs_project_path ON wbs(project_id, path);
CREATE INDEX IF NOT EXISTS idx_suppliers_project_code ON suppliers(project_id, supplier_code);
CREATE INDEX IF NOT EXISTS idx_warehouses_project_code ON warehouses(project_id, warehouse_code);
CREATE INDEX IF NOT EXISTS idx_commodity_codes_project_code ON commodity_codes(project_id, engineered_code);
CREATE INDEX IF NOT EXISTS idx_equipment_list_project_tag ON equipment_list(project_id, engineered_tag);
CREATE INDEX IF NOT EXISTS idx_mtos_project_number ON mtos(project_id, mto_number);
CREATE INDEX IF NOT EXISTS idx_mto_line_items_mto ON mto_line_items(mto_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_project_number ON purchase_orders(project_id, po_number);
CREATE INDEX IF NOT EXISTS idx_po_line_items_po ON po_line_items(po_id);
CREATE INDEX IF NOT EXISTS idx_po_line_items_scn ON po_line_items(scn_number) WHERE scn_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_scns_project_number ON scns(project_id, scn_number);
CREATE INDEX IF NOT EXISTS idx_scn_line_items_scn ON scn_line_items(scn_id);
CREATE INDEX IF NOT EXISTS idx_receipts_project_number ON receipts(project_id, receipt_number);
CREATE INDEX IF NOT EXISTS idx_receipt_line_items_receipt ON receipt_line_items(receipt_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_inventory_lookup ON warehouse_inventory(warehouse_id, commodity_code_id, equipment_id);
CREATE INDEX IF NOT EXISTS idx_inventory_reservations_inventory ON inventory_reservations(inventory_id, required_by_date);
CREATE INDEX IF NOT EXISTS idx_documents_project ON documents(project_id);
CREATE INDEX IF NOT EXISTS idx_document_assoc_entity ON document_associations(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_traceability_project_certificate ON traceability_certificates(project_id, certificate_number);
CREATE INDEX IF NOT EXISTS idx_emergency_incidents_project ON emergency_incidents(project_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_table_record ON audit_log(table_name, record_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_changed_at ON audit_log(changed_at);
